// Comments constants
export const REQUEST_COMMENT = 'REQUEST_COMMENT';
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENT = 'RECEIVE_COMMENT';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const SET_COMMENTS_ERRORS = 'SET_COMMENTS_ERRORS';